// Re-ekspor domain battle: state, resource, efek, AI, hasil, command.

export {
  HERO_MANA_CAP,
  HERO_SKILL_ENERGY_COST,
  HERO_ULTIMATE_ENERGY_COST,
  ENERGY_CAP,
  ENEMY_SKILL_BASE_COST,
  PIECE_VALUES,
  cloneBattle,
  createInitialBattle,
  restoreBattleSnapshot,
  snapshotBattle,
} from './state.ts';
export type {
  BattleDeps,
  BattleSnapshot,
  BattleState,
  Board,
  BossDef,
  CardDef,
  CardKind,
  CastlingRights,
  ChessRules,
  Color,
  CommandResult,
  EnemyPreparedSkill,
  HeroDef,
  HistoryEntry,
  InitialBattleInput,
  Move,
  MovementMods,
  Piece,
  PieceType,
  PromotionChoice,
  RandomSource,
  Square,
} from './state.ts';
export {
  canPlayCard,
  currentCardCost,
  drawCard,
  gainEnemyEnergy,
  gainEnergy,
  gainMana,
  loseEnergy,
  loseEnemyEnergy,
  makeHand,
  payCardCost,
  refundCardCost,
  replaceHandSlot,
  rerollCost,
  rerollLimit,
} from './resources.ts';
export type { CardPlayability } from './resources.ts';
export {
  PIECE_NAMES,
  CARD_TARGET_PROMPTS,
  TARGET_CARD_IDS,
  advanceBossReplyEffects,
  applyAegisUltimate,
  applyBaraSkill,
  applyInstantCard,
  applyPawnRushUltimate,
  applyPendingEnemyDrain,
  applySkipUltimate,
  applyWhiteMoveTriggers,
  battleLegalMoves,
  battleLegalMovesFrom,
  beginHeroTarget,
  canReviveWhitePiece,
  clearPieceEffects,
  commitBattleMove,
  completeHeroTarget,
  findPieceSquare,
  hasBlackJokerTarget,
  hasWhiteJokerTarget,
  resolveCardTarget,
  resolveHeroTarget,
  revivalTargets,
} from './effects.ts';
export type { CommittedMove, TargetResolution } from './effects.ts';
export {
  applyBossRule,
  blockadeAllowsBossMove,
  chooseComputerMove,
  describeEnemyPlan,
  resolveEnemySkill,
} from './ai.ts';
export type { EnemyPlanKind, EnemyTelegraph } from './ai.ts';
export { checkOutcome, claimBattleReward } from './result.ts';
export type { OutcomeCheck } from './result.ts';
export {
  canUndo,
  cancelTarget,
  choosePromotion,
  continueAfterWhiteMove,
  finishFullTurn,
  movePiece,
  playCard,
  rerollHand,
  resolveTarget,
  restartBattle,
  runBlackReply,
  selectPiece,
  tapSquare,
  undoTurn,
  useHeroSkill,
  useHeroUltimate,
} from './commands.ts';
